sudo: required

language: python

python:
  - 2.7

services:
  - mysql

before_install:
  - wget http://files.vlabs.ac.in/downloads/emacs.tar.gz
  - tar -xvzf emacs.tar.gz
  - cp -r emacs /home/travis/
  - echo $(pwd)
  - make
  - pip install oursql Flask Flask-SQLAlchemy requests flask-cors flask-testing pyyaml
 
install: 
  - sudo apt-get install emacs -y
  
script: 
  - chmod +x run_tests.sh
  - ./run_tests.sh
after_success:
  - cat /etc/issue

