sudo: required

language: python

python:
  - 2.7

services:
  - mysql

before_install:
  - wget http://files.vlabs.ac.in/downloads/emacs.tar.gz
  - tar -xvzf emacs.tar.gz
  - cp -r emacs /home/travis/
  - make build  
 
install: 
  - pip install oursql Flask Flask-SQLAlchemy requests flask-cors flask-testing pyyaml   
  
before_script:
  - cd build/code
  - export PYTHONPATH=$(pwd)
  
script:
  - cd ../../
  - chmod +x run_tests.sh
  - ./run_tests.sh
  
after_success:
  - cat /etc/issue

