sudo: required

language: python

python:
  - 2.7

before_install:
  - wget http://files.vlabs.ac.in/downloads/emacs.tar.gz
  - tar -xvzf emacs.tar.gz
  - cp -r emacs /home/travis/
  - make build  
  - openssl aes-256-cbc -K $encrypted_d94e2007530f_key -iv $encrypted_d94e2007530f_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - chmod 600 deploy_rsa

 
install: 
  - pip install oursql Flask Flask-SQLAlchemy requests flask-cors flask-testing pyyaml   
  
before_script:
  - cd build/code
  - export PYTHONPATH=$(pwd)
  
script:
  - cd ../../
  - chmod +x run_tests.sh
  - ./run_tests.sh
  - rsync -e "ssh -p 22 -i deploy_rsa -o 'StrictHostKeyChecking no'" -avz makefile sripathi@ssh-tunnel.vlabs.ac.in:/tmp/file_to_upload





